# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_fav',
            field=models.BooleanField(default='false'),
        ),
    ]
